src/fasta/reader.jl, src/fastq/reader.jl
Trying to fix https://github.com/BioJulia/FASTX.jl/issues/8
Not sure this fixes all, but it seems at least to make me able to read fastq records through a `NoopStream` as follows:
```
julia> open(NoopStream, fq_filename) do stream
reader = FASTQ.Reader(stream)
record = FASTQ.Record()
while !eof(reader)
read!(reader, record)
println(record)
end
end
```
=> Handle case where input is a TranscodingStream.

docs/src/manual/fasta.md
To save 30mins of pain because new Julia users are still learning the syntax.
=> add FASTA.identifier(record) example in docs

docs/src/manual/fasta.md, docs/src/manual/fastq.md
Sequence files, especially fastq files, are often compressed. This adds some notes on how to read Gzip compressed files to FASTA and FASTQ.
Credit @js135005 [on discourse](https://discourse.julialang.org/t/streaming-gziped-file-to-fastq-reader-where-to-add-method/36266) for pointing me to `CodecZlib`.
=> Add docs on reading gzipped files

src/fastq/readrecord.jl
We can improve the speed of parsing unzipped FASTQ files with about 60% if we disable the boundscheck.
* The FASTA parser has boundscheck disabled, too.
* The readrecord code does not manipulate the index to the data, so it should be safe
=> Inbounds FASTQ parser

src/fasta/record.jl, src/fastq/record.jl
FASTX used `BioSequences.encode_copy!` despite (presumably?) being an internal function. Here, I've replaced it with `copyto!`, implemented in BioSequences by a recent PR.
How do we do this without causing too much breakage? Should we wait until a new release of BioSequences have been made, then change the lower bound of FASTX's dependency to the new release?
I also added a `Base.copy!` method. This is useful when iterating over a FASTA file, mutating a single sequence.
=> Remove use of internal `encode_copy!` [DO NOT MERGE]

src/fasta/record.jl
A small change to avoid a `BoundsError` when trying to copy a `FastaRecord` with length-zero sequence to a sequence.
=> Fix zero-length copy

src/fastq/readrecord.jl, test/runtests.jl
This is a bugfix to issue #25 .
Briefly, the problem was that, in `readrecord.jl`, at the state transition after a record, `@escape` was called. On UNIX systems, this would occur at the `\n` byte after a record, which would put the machine in a state immediately before the next record, or at EOF if at last record. However, on Windows system where the newline is two bytes (`\r\n`), this would occur after only the `\r` byte had been consumed. This means that the machine would not be at EOF, even though all records had been consumed.
=> Fix windows newline bug (issue 25)

README.md, src/fasta/index.jl, src/fasta/reader.jl, test/runtests.jl
Addresses issue #29. This PR also includes #30 .
Changes:
* `FASTA.Index` now uses a `Dict` instead of a vector of names. This is slower to construct and more memory inefficient, but obviously has the benefit of constant-time lookup in the index. I'd argue that if you create an index, you do so specifically in order to have fast lookup, and you probably don't care about the few extra kilobytes of RAM used, or miliseconds when constructing the index.
* Added a new method: `extract(r::Reader, A::Alphabet, s::AbstractString, u::UnitRange)`, which does the same as `sequence(A, r[s], u)`, but does not load the entire sequence into memory first.
=> Add constant time fasta index seeking [NEED REVIEW]

docs/src/manual/fastq.md, src/fastq/fastq.jl, src/fastq/fastqread.jl, src/fastq/record.jl, test/runtests.jl
This PR implements the following changes:
This implements Base.getindex to allow subsetting of fastq records using string syntax:
```
record = FASTQ.Record("""
@SRR1238088.1.1 HWI-ST499:111:D0G94ACXX:1:1101:1173:2105
AAGCTCATGACCCGTCTTACCTACACCCTTGACGAGATCGAAGGA
+SRR1238088.1.1 HWI-ST499:111:D0G94ACXX:1:1101:1173:2105
@BCFFFDFHHHHHJJJIJIJJIJJJJJJJJIJJJJIIIJJJIJJJ
""")
julia> record[3:6]
FASTX.FASTQ.Record:
identifier: SRR1238088.1.1
description: HWI-ST499:111:D0G94ACXX:1:1101:1173:2105
sequence: GCTC
quality: UInt8[0x22, 0x25, 0x25, 0x25]
```
This addition was proposed in #34
=> Subset fastq record using string syntax

src/fastq/readrecord.jl
MWE:
```julia
using FASTX
s = join(collect("@A+J@A/J"), '\n')
println(collect(FASTQ.Reader(IOBuffer(s))))
```
Output:
```julia
ERROR: LoadError: ArgumentError: malformed FASTQ file at line 6
```
But the mistake is actually on line 7, not line 6. The problem was a previous change I had made in #28 , where I accidentally had the `@escape` action before the `@countline` action, so the latter was never taken.
=> Fix FASTQ line counting bug

src/fasta/readrecord.jl, src/fastq/readrecord.jl, test/runtests.jl
MWE before:
```
julia> dump(first(iterate(FASTA.Reader(IOBuffer(">A \nTAG\n")))))
FASTX.FASTA.Record
data: Array{UInt8}((8,)) UInt8[0x3e, 0x41, 0x20, 0x0a, 0x54, 0x41, 0x47, 0x0a]
filled: UnitRange{Int64}
start: Int64 1
stop: Int64 8
identifier: UnitRange{Int64}
start: Int64 2
stop: Int64 2
description: UnitRange{Int64}
start: Int64 4
stop: Int64 7
sequence: UnitRange{Int64}
start: Int64 1
stop: Int64 0
```
Note that the sequence `TAG` is parsed as part of the description.
After:
```
julia> dump(first(iterate(FASTA.Reader(IOBuffer(">A \nTAG\n")))))
FASTX.FASTA.Record
data: Array{UInt8}((7,)) UInt8[0x3e, 0x41, 0x20, 0x0a, 0x54, 0x41, 0x47]
filled: UnitRange{Int64}
start: Int64 1
stop: Int64 7
identifier: UnitRange{Int64}
start: Int64 2
stop: Int64 2
description: UnitRange{Int64}
start: …
```
=> Fix description newline bug

src/fasta/fasta.jl, src/fasta/record.jl, src/fastq/record.jl, test/runtests.jl
As described in #40 , this adds a small PR to obtain the sequence and quality from FASTA/FASTQ files without allocating a new vector.
=> Add quality and sequence iterator

docs/src/manual/fasta.md, docs/src/manual/fastq.md
The current docs don't use the `open/do/end` syntax and then just provide a warning at the end. I modified the docs to use it in most examples and move the explanation earlier in the docs to when the `open` convenience syntax is introduced.
=> Model good behavior with do block syntax

src/fasta/record.jl, src/fastq/record.jl
Fix bug. MWE:
```julia
julia> isnothing(FASTA.header(FASTA.Record("> hello\nTAG")))
true
```
I did not consider that a record may have an empty identifier but not an empty description.
=> Fix header code

src/fastq/readrecord.jl, test/runtests.jl
Fix issue #48 by allowing trailing newlines after FASTQ file.
=> Allow trailing newlines for FASTQ files

src/fasta/readrecord.jl, test/runtests.jl
Change the FSM definition for `sequence` to allow the following file: `">A\nA "` (i.e. allow whitespace after sequence lines)
I'm really not satisfied with this whack-a-mole process of continuing to refine the FSM definition until we've exhaused all the edge cases. We need a better test suite, or else create our own FASTA spec. Crossref #37 .
At any case, this fixes the issue and doesn't introduce any new issues that I'm aware of.
=> Allow trailing whitespace in sequences

src/FASTX.jl, test/runtests.jl
For issue #50 
For a consistent conversion between HTS formats, we'll probably need a separate package with a more generic version of the `transcode` function I've implemented here. Possibly using `convert` and `promote`, although for this example a simple `FASTA.Record` constructor accepting a `FASTQ.Record` was enough.
This PR implements the following changes:
_(Please tick any or all of the following that are applicable)_
=> Transcode between FASTQ & FASTA files

README.md, src/FASTX.jl, src/fasta/fasta.jl, src/fasta/record.jl, src/fastq/fastq.jl, src/fastq/record.jl
This exports `hassequence`, `hasdescription`, `header`, and other functions that are user-facing, but not exported.
I have not exported `FASTQRead`, because we do not agree about whether this should ultimately be in FASTX. https://github.com/BioJulia/FASTX.jl/pull/35#issuecomment-713198555
=> Export all user-facing functions

.github/workflows/UnitTesting.yml, Project.toml
Since 1.6 is the oldest currently supported version of Julia, we might as well do this.
=> Update Julia requirement to 1.6

.github/workflows/UnitTesting.yml, Project.toml, src/fasta/record.jl, src/fastq/record.jl, test/runtests.jl
This creates a new version of FASTX using the latest BioSequences/BioSymbols. It contains no breaking changes.
I think FASTX could use a more thorough release where e.g. the tests are fixed up. But that's a larger undertaking, this is just to allow BioSequences v3 to be used with FASTX.
=> Bump BioSequences/BioSymbols to v3/v5

.github/workflows/TagBot.yml, Project.toml, README.md, src/FASTX.jl, src/fasta/fasta.jl, src/fasta/record.jl, src/fastq/fastq.jl, src/fastq/record.jl, test/runtests.jl
Currently, `header`, `identifier` and `description` returns `String`, which forces needless allocations. This PR adds the dependency `StringViews`, which allows the creation of an `AbstractString` from any `AbstractVector{UInt8}`.
The aforementioned functions now return these string views backed by a view into the data buffer.
This change is breaking.
=> Return header, identifier and desc as string views

docs/src/manual/fasta.md, docs/src/manual/fastq.md, src/fasta/reader.jl, src/fasta/writer.jl, src/fastq/reader.jl, src/fastq/writer.jl
Simple documentation change. Should also be ported to v2.
=> Clarify that streams take ownership of IO

docs/src/manual/fasta.md
=> Fix missing character in docs example

Project.toml, src/FASTX.jl, src/workload.jl
The small dependency SnoopPrecompile allows more efficient precompile statements
in packages. Hence, this change somewhat reduces latency of FASTX.jl, and is
expected to cause even larger latency reductions when Julia's compiler improves
=> Add SnoopPrecompile

src/workload.jl, test/test.fasta, test/test.fastq
Improve precompilation by operating on files instead of IOBuffers. This is more representative of a realistic workload.
=> Improve precompilation

CHANGELOG.md, Project.toml, src/fastq/reader.jl, test/fasta/io.jl, test/fastq/io.jl
These functions were not tested directly, and indeed did not work for FASTQ, due to a typo.
Closes #95
=> Fix Base.read!(::Reader, ::Record) and add tests

src/fasta/index.jl, test/fasta/index.jl
This allows the user to turn an `Index` into a string easily, and also makes it easier to test the indices.
=> Add Base.print(::IO, ::Index)

.github/workflows/UnitTesting.yml
This combination no longer exists, since the latests versions of MacOS does not run on x86 processors anymore.
=> Disable CI for x86 macOS-latest

.github/workflows/UnitTesting.yml
* Run Windows on 1.7, not LTS, to avoid slow registry cloning and speed up CI severalfold
* Run MacOS on 1.9 also, the first version with MacOS ARM tier 1 support
* Do not specify architechture
* Upgrade to the newer versions of actions
=> Upgrade CI

.github/workflows/UnitTesting.yml, Project.toml
Now that Julia 1.10 is LTS, we can drop support for older versions.
In preparation for an upcoming PR that makes use of `const` fields - a 1.8 feature.
Also, this allows us to simplify the CI.
=> Drop support for Julia <1.10

Project.toml, src/FASTX.jl
To allow the BioSequences FASTX extension to be supported with Julia <1.9, a few hacks had to be done.
Remove these hacks, as we now longer support these versions.
=> Delete workaround for compat with extensions
